# general settings
name: ECFNet-AlignFormer-ChangeLRSched
model_type: ECFNetModel
scale: 1
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: syn_pair_train
    type: TripleImageDataset
    dataroot_gt: datasets/iphone_dataset/AlignFormer/train/
    dataroot_ref: datasets/iphone_dataset/mask/train/
    dataroot_lq: datasets/iphone_dataset/lq/train/
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 50
    prefetch_mode: ~

  val:
    name: syn_pair_val
    type: TripleImageDataset
    dataroot_gt: datasets/iphone_dataset/AlignFormer/test_sub/
    dataroot_ref: datasets/iphone_dataset/mask/test_sub/
    dataroot_lq: datasets/iphone_dataset/lq/test_sub/
    filename_tmpl: '{}'
    io_backend:
      type: disk

#### network structures
network_g:
  type: ECFNet
  in_nc: 3
  out_nc: 3
  num_res: 8

# path
path:
  pretrain_network_g: ~
#  param_key_g: 'params_ema'
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [100000, 100000, 100000, 100000]
    restart_weights: [1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: ECFNetLoss
    loss_weight: !!float 1.0



# validation settings
val:
  val_freq: !!float 2e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 2e4

  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500