# general settings
name: SRGAN_AlignFormer
folder_suffix: AF
model_type: SRGANModel
scale: 1
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: syn_pair_train
    type: TripleImageDataset
    dataroot_gt: datasets/iphone_dataset/ref/train/
    dataroot_ref: datasets/iphone_dataset/mask/train/
    dataroot_lq: datasets/iphone_dataset/lq/train/
    meta_info_file: ~
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 10
    prefetch_mode: ~

  val:
    name: syn_pair_val
    type: TripleImageDataset
    dataroot_gt: datasets/iphone_dataset/ref/test_sub/
    dataroot_ref: datasets/iphone_dataset/mask/test_sub/
    dataroot_lq: datasets/iphone_dataset/lq/test_sub/
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: SRGenerator
  io_channels: 3

network_d:
  type: SRDiscriminator
  io_channels: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 100000]
    gamma: 0.1

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: ModifiedMSELoss
    loss_weight: !!float 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 250
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29165
